#!/usr/bin/env bash


if [[ $mydbg -gt 0 ]] ; then
    echo "Loading bash_profile.local"
fi


key=$(uname -n)

case $key:
    chimay)
        #loading entware
        source /opt/etc/profile
    affli)
        ;;
esac


# loading conda
