#!/usr/bin/env bash

filename=bash_aliases
echo "$(date +"%Y%m%d %H:%M:%S");Loading $filename" >> ~/.bash_log



#
# Directory aliases
#

alias ..="cd .."
alias dl="cd ~/Downloads"
alias h="history"


# For ls
alias ll="ls -lF"
alias la="ls -laF"


# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# Enable aliases to be sudo’ed
alias sudo="sudo "

# Get week number
alias week="date +%V"
# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"


# Reload the shell by invoking a login shell
alias reload="exec ${SHELL} -l"
