#!/usr/bin/env bash

mydbg=1

if [[ $mydbg -gt 0 ]] ; then
    echo "Loading .bashrc"
fi

local file="~/.dotfiles/shell/bash_profile"

if [[ -r "$file" ]] && [[ -f "$file"]]; then
    source "$file"
else
    printf "> Cannot load $file"
fi
