#!/usr/bin/env bash


filename=bash_profile_local
echo "$(date +"%Y%m%d %H:%M:%S");$$;$(tty);Loading $filename" >> ~/.bash_log



key=$(uname -n | md5sum | cut -d\  -f1)

case $key in
    4bb2471c6b1dcae858d5150497bb9110) #Syno
        #loading entware
        source /opt/etc/profile
        # loading miniconda
        export PATH="${HOME}/miniconda3/bin:$PATH"

        ;;
    58c336705cf447b0ba4d4417f969e07a) #mbp
        #loading conda
        export PATH="${HOME}/anaconda3/bin:${PATH}"

	#wol
	#alias wol="wakeonlan -i 192.168.76.230 00:11:32:5C:41:6F"

        ;;
    *)
        echo "No local configuration for $(uname -n) (key: $key)"
        ;;
esac

unset key


if [ -f ${HOME}/.bash_profile.local ] && [ -r ${HOME}/.bash_profile.local]; then
    echo "$(date +"%Y%m%d %H:%M:%S");Loading local config (${HOME}/.bash_profile.local" >> ~/.bash_log
    source ${HOME}/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
fi
